### ISSUE TITLE
errors in dev mode

### ISSUE THREAD

**Issue by michalbe** [ennovum/chandler#1]
When running `npm run dev` I get this kind of error:

``` javascript
Finished 'client-test:start' after 4.29 ms

events.js:72

        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at EventEmitter.listen (/home/michalbe/devel/chandler/node_modules/express/lib/application.js:617:24)
    at App.run (/home/michalbe/devel/chandler/dev/server/index.js:146:24)
    at Object.defineProperty.value (/home/michalbe/devel/chandler/dev/server/index.js:63:6)
    at __webpack_require__ (/home/michalbe/devel/chandler/dev/server/index.js:20:30)
    at Object.obj.__esModule.default (/home/michalbe/devel/chandler/dev/server/index.js:47:19)
    at __webpack_require__ (/home/michalbe/devel/chandler/dev/server/index.js:20:30)

exit (8)
```

**Comment by ennovum** [comment]
Do you encounter it always or only sometimes?

**Comment by michalbe** [comment]
## Always.

Sent directly from my brain Saturday, 26 September 2015, 08:52PM +02:00 from Grzegorz Wasiak < notifications@github.com> :

**Comment by michalbe** [comment]
Ok, my bad, works fine after reboot. Probably previous instance of the serve was still on.
